# Generated by Django 3.2.20 on 2023-12-19 15:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must start with +(country code)', regex='^\\+(\\d+)$')])),
                ('reference_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Others', 'Others')], max_length=10)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('manufacture_date', models.DateField()),
                ('make', models.CharField(max_length=50)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.participant')),
            ],
        ),
    ]
