# Generated by Django 3.2.20 on 2023-12-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='name',
        ),
    ]
