# Generated by Django 3.2.20 on 2023-12-20 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_participant_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='dob',
            new_name='DOB',
        ),
    ]
