# Generated by Django 3.2.20 on 2023-12-21 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_dob_participant_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='DOB',
            new_name='dob',
        ),
    ]
