# Generated by Django 3.2.20 on 2023-12-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_dob_participant_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='license',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
